apiVersion: v1
kind: ConfigMap

metadata:
  name: appointment-config
  namespace: hospital

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-appointment:3306/AppointmentService
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

  EUREKA_SERVER_URL: http://eureka:8761/eureka/
