apiVersion: v1
kind: ConfigMap

metadata:
  name: doctor-config
  namespace: hospital

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-doctor:3306/DoctorService
  EUREKA_SERVER_URL: http://eureka:8761/eureka/
