apiVersion: v1
kind: ConfigMap

metadata:
  name: login-config
  namespace: hospital

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-login:3306/LoginService
  EUREKA_SERVER_URL: http://eureka:8761/eureka/
