apiVersion: v1
kind: ConfigMap

metadata:
  name: medical-history-config
  namespace: hospital

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-medical-history:3306/MedicalHistoryService
  EUREKA_SERVER_URL: http://eureka:8761/eureka/
