apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: vamshi925/login-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8083

        envFrom:
        - configMapRef:
            name: login-config

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          failureThreshold: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 20
