apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: vamshi925/notification-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8087

        envFrom:
        - configMapRef:
            name: notification-config

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          failureThreshold: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 20
