apiVersion: v1
kind: ConfigMap

metadata:
  name: medical-history-config
  namespace: {{ .Values.namespace }}

  labels:
{{ include "hospital.labels" . | nindent 4 }}

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-medical-history:3306/MedicalHistoryService
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  EUREKA_SERVER_URL: http://eureka:8761/eureka/
