apiVersion: v1
kind: Service

metadata:
  name: mysql-medical-history
  namespace: hospital

spec:
  clusterIP: None

  selector:
    app: mysql-medical-history

  ports:
  - port: 3306
    targetPort: 3306
