apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-notification
  namespace: hospital

spec:
  serviceName: mysql-notification

  replicas: 1

  selector:
    matchLabels:
      app: mysql-notification

  template:
    metadata:
      labels:
        app: mysql-notification

    spec:
      containers:
      - name: mysql

        image: mysql:8.4

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-notification-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          value: NotificationService

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage

    spec:
      accessModes:
      - ReadWriteOnce

      resources:
        requests:
          storage: 5Gi
