{{- range $name, $svc := .Values.services }}

{{ include "hospital.deployment" (dict
"name" $name
"namespace" $.Values.namespace
"replicaCount" $svc.replicaCount
"image" $svc.image
"service" $svc.service
"resources" $svc.resources
"probes" $svc.probes
"configMap" $svc.configMap
"Chart" $.Chart
"Release" $.Release
) }}

---

{{- end }}
